version: '3.3'

services:
  frontend:
    container_name: cat-monitoring
    image: cat-monitoring
    build: 
      context: ./cat-monitoring
      dockerfile: Dockerfile
    ports:
      - "4200:80"